=== Flameeyes/hypnos/xml/dtds/skills.dtd
<!-- elements in schedules -->
<!ELEMENT skills (skill*)>

<!-- data inside schedules is the name of the function to call -->
<!ELEMENT skill (skillpoint*)>
<!ATTLIST skill
	name CDATA #REQUIRED
	str CDATA "0"
	dex CDATA "0"
	int CDATA "0"
	unhideOnUse (true|false) "true"
	unhideOnFail (true|false) "true"
>

<!ELEMENT skillpoint EMPTY>
<!ATTLIST skillpoint
	base CDATA #REQUIRED
	success CDATA #REQUIRED
	failire CDATA #REQUIRED
>

=== Flameeyes/hypnos/xml/config/skills.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE skills SYSTEM "http://hypnos.berlios.de/dtds/skills.dtd">
<skills>
  <skill name="skAlchemy" dex="50" int="50">
    <skillpoint base="0" success="75" failure="50" />
    <skillpoint base="100" success="70" failure="30" />
    <skillpoint base="200" success="65" failure="25" />
    <skillpoint base="300" success="60" failure="20" />
    <skillpoint base="400" success="55" failure="15" />
    <skillpoint base="500" success="50" failure="10" />
    <skillpoint base="600" success="30" failure="5" />
    <skillpoint base="700" success="25" failure="2" />
    <skillpoint base="800" success="20" failure="1" />
    <skillpoint base="900" success="15" failure="0" />
    <skillpoint base="990" success="10" failure="0" />
    <skillpoint base="1000" success="0" failure="0" />
  </skill>
  <skill name="skAnatomy" str="10" dex="10" int="80" unhideOnUse="false">
    <skillpoint base="0" success="75" failure="50" />
    <skillpoint base="100" success="70" failure="30" />
    <skillpoint base="200" success="65" failure="25" />
    <skillpoint base="300" success="60" failure="20" />
    <skillpoint base="400" success="55" failure="15" />
    <skillpoint base="500" success="50" failure="10" />
    <skillpoint base="600" success="30" failure="5" />
    <skillpoint base="700" success="25" failure="2" />
    <skillpoint base="800" success="20" failure="1" />
    <skillpoint base="900" success="15" failure="0" />
    <skillpoint base="990" success="10" failure="0" />
    <skillpoint base="1000" success="0" failure="0" />
  </skill>
  <skill name="skAnimalLore" int="100">
    <skillpoint base="0" success="75" failure="50" />
    <skillpoint base="100" success="70" failure="30" />
    <skillpoint base="200" success="65" failure="25" />
    <skillpoint base="300" success="60" failure="20" />
    <skillpoint base="400" success="55" failure="15" />
    <skillpoint base="500" success="50" failure="10" />
    <skillpoint base="600" success="30" failure="5" />
    <skillpoint base="700" success="25" failure="2" />
    <skillpoint base="800" success="20" failure="1" />
    <skillpoint base="900" success="15" failure="0" />
    <skillpoint base="990" success="10" failure="0" />
    <skillpoint base="1000" success="0" failure="0" />
  </skill>
  <skill name="skItemID" int="100">
    <skillpoint base="0" success="75" failure="50" />
    <skillpoint base="100" success="70" failure="30" />
    <skillpoint base="200" success="65" failure="25" />
    <skillpoint base="300" success="60" failure="20" />
    <skillpoint base="400" success="55" failure="15" />
    <skillpoint base="500" success="50" failure="10" />
    <skillpoint base="600" success="30" failure="5" />
    <skillpoint base="700" success="25" failure="2" />
    <skillpoint base="800" success="20" failure="1" />
    <skillpoint base="900" success="15" failure="0" />
    <skillpoint base="990" success="10" failure="0" />
    <skillpoint base="1000" success="0" failure="0" />
  </skill>
  <skill name="skArmsLore" str="80" dex="10" int="10">
    <skillpoint base="0" success="75" failure="50" />
    <skillpoint base="100" success="70" failure="30" />
    <skillpoint base="200" success="65" failure="25" />
    <skillpoint base="300" success="60" failure="20" />
    <skillpoint base="400" success="55" failure="15" />
    <skillpoint base="500" success="50" failure="10" />
    <skillpoint base="600" success="30" failure="5" />
    <skillpoint base="700" success="25" failure="2" />
    <skillpoint base="800" success="20" failure="1" />
    <skillpoint base="900" success="15" failure="0" />
    <skillpoint base="990" success="10" failure="0" />
    <skillpoint base="1000" success="0" failure="0" />
  </skill>
  <skill name="skParrying" str="75" dex="25">
    <skillpoint base="0" success="75" failure="50" />
    <skillpoint base="100" success="70" failure="30" />
    <skillpoint base="200" success="65" failure="25" />
    <skillpoint base="300" success="60" failure="20" />
    <skillpoint base="400" success="55" failure="15" />
    <skillpoint base="500" success="50" failure="10" />
    <skillpoint base="600" success="30" failure="5" />
    <skillpoint base="700" success="25" failure="2" />
    <skillpoint base="800" success="20" failure="1" />
    <skillpoint base="900" success="15" failure="0" />
    <skillpoint base="990" success="10" failure="0" />
    <skillpoint base="1000" success="0" failure="0" />
  </skill>
  <skill name="skBegging">
    <skillpoint base="0" success="75" failure="50" />
    <skillpoint base="100" success="70" failure="30" />
    <skillpoint base="200" success="65" failure="25" />
    <skillpoint base="300" success="60" failure="20" />
    <skillpoint base="400" success="55" failure="15" />
    <skillpoint base="500" success="50" failure="10" />
    <skillpoint base="600" success="30" failure="5" />
    <skillpoint base="700" success="25" failure="2" />
    <skillpoint base="800" success="20" failure="1" />
    <skillpoint base="900" success="15" failure="0" />
    <skillpoint base="990" success="10" failure="0" />
    <skillpoint base="1000" success="0" failure="0" />
  </skill>
  <skill name="skBlacksmithing" str="100">
    <skillpoint base="0" success="75" failure="50" />
    <skillpoint base="100" success="70" failure="30" />
    <skillpoint base="200" success="65" failure="25" />
    <skillpoint base="300" success="60" failure="20" />
    <skillpoint base="400" success="55" failure="15" />
    <skillpoint base="500" success="50" failure="10" />
    <skillpoint base="600" success="30" failure="5" />
    <skillpoint base="700" success="25" failure="2" />
    <skillpoint base="800" success="20" failure="1" />
    <skillpoint base="900" success="15" failure="0" />
    <skillpoint base="990" success="10" failure="0" />
    <skillpoint base="1000" success="0" failure="0" />
  </skill>
  <skill name="skBowcraft" str="40" dex="60">
    <skillpoint base="0" success="75" failure="50" />
    <skillpoint base="100" success="70" failure="30" />
    <skillpoint base="200" success="65" failure="25" />
    <skillpoint base="300" success="60" failure="20" />
    <skillpoint base="400" success="55" failure="15" />
    <skillpoint base="500" success="50" failure="10" />
    <skillpoint base="600" success="30" failure="5" />
    <skillpoint base="700" success="25" failure="2" />
    <skillpoint base="800" success="20" failure="1" />
    <skillpoint base="900" success="15" failure="0" />
    <skillpoint base="990" success="10" failure="0" />
    <skillpoint base="1000" success="0" failure="0" />
  </skill>
  <skill name="skPeacemaking" dex="50" int="50">
    <skillpoint base="0" success="75" failure="50" />
    <skillpoint base="100" success="70" failure="30" />
    <skillpoint base="200" success="65" failure="25" />
    <skillpoint base="300" success="60" failure="20" />
    <skillpoint base="400" success="55" failure="15" />
    <skillpoint base="500" success="50" failure="10" />
    <skillpoint base="600" success="30" failure="5" />
    <skillpoint base="700" success="25" failure="2" />
    <skillpoint base="800" success="20" failure="1" />
    <skillpoint base="900" success="15" failure="0" />
    <skillpoint base="990" success="10" failure="0" />
    <skillpoint base="1000" success="0" failure="0" />
  </skill>
  <skill name="skCamping" str="60" dex="20" int="20">
    <skillpoint base="0" success="75" failure="50" />
    <skillpoint base="100" success="70" failure="30" />
    <skillpoint base="200" success="65" failure="25" />
    <skillpoint base="300" success="60" failure="20" />
    <skillpoint base="400" success="55" failure="15" />
    <skillpoint base="500" success="50" failure="10" />
    <skillpoint base="600" success="30" failure="5" />
    <skillpoint base="700" success="25" failure="2" />
    <skillpoint base="800" success="20" failure="1" />
    <skillpoint base="900" success="15" failure="0" />
    <skillpoint base="990" success="10" failure="0" />
    <skillpoint base="1000" success="0" failure="0" />
  </skill>
  <skill name="skCarpentry" str="75" dex="25">
    <skillpoint base="0" success="75" failure="50" />
    <skillpoint base="100" success="70" failure="30" />
    <skillpoint base="200" success="65" failure="25" />
    <skillpoint base="300" success="60" failure="20" />
    <skillpoint base="400" success="55" failure="15" />
    <skillpoint base="500" success="50" failure="10" />
    <skillpoint base="600" success="30" failure="5" />
    <skillpoint base="700" success="25" failure="2" />
    <skillpoint base="800" success="20" failure="1" />
    <skillpoint base="900" success="15" failure="0" />
    <skillpoint base="990" success="10" failure="0" />
    <skillpoint base="1000" success="0" failure="0" />
  </skill>
  <skill name="skCartography" dex="50" int="50">
    <skillpoint base="0" success="75" failure="50" />
    <skillpoint base="100" success="70" failure="30" />
    <skillpoint base="200" success="65" failure="25" />
    <skillpoint base="300" success="60" failure="20" />
    <skillpoint base="400" success="55" failure="15" />
    <skillpoint base="500" success="50" failure="10" />
    <skillpoint base="600" success="30" failure="5" />
    <skillpoint base="700" success="25" failure="2" />
    <skillpoint base="800" success="20" failure="1" />
    <skillpoint base="900" success="15" failure="0" />
    <skillpoint base="990" success="10" failure="0" />
    <skillpoint base="1000" success="0" failure="0" />
  </skill>
  <skill name="skCooking" dex="40" int="60">
    <skillpoint base="0" success="75" failure="50" />
    <skillpoint base="100" success="70" failure="30" />
    <skillpoint base="200" success="65" failure="25" />
    <skillpoint base="300" success="60" failure="20" />
    <skillpoint base="400" success="55" failure="15" />
    <skillpoint base="500" success="50" failure="10" />
    <skillpoint base="600" success="30" failure="5" />
    <skillpoint base="700" success="25" failure="2" />
