=== Flameeyes/hypnos/xml/dtds/start.dtd
<!-- elements in start -->
<!ELEMENT start (location+)>

<!-- data inside schedules is the name of the function to call -->
<!ELEMENT location (city|place|position)>
<!ELEMENT city (#PCDATA) >
<!ELEMENT place (#PCDATA) >
<!ELEMENT position EMPTY>

<!ATTLIST position
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>

=== Flameeyes/hypnos/xml/config/start.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE start SYSTEM "http://hypnos.berlios.de/dtds/start.dtd">
<!--
  Default start locations.
  Please note that there should be *exaclty* 9 locations, else the last one is
  dupe for the ones empty.
-->
<start>
  <location>
    <city>Yew</city>
    <place>The Sturdy Bow</place>
    <position x="567" y="978" z="0" />
  </location>
  <location>
    <city>Minoc</city>
    <place>The Barnacle Tavern</place>
    <position x="2477" y="407" z="15" />
  </location>
  <location>
    <city>Britain</city>
    <place>Sweet Dreams Inn</place>
    <position x="1496" y="1629" z="10" />
  </location>
  <location>
    <city>Moonglow</city>
    <place>The Scholars Inn</place>
    <position x="4404" y="1169" z="0" />
  </location>
  <location>
    <city>Trinsic</city>
    <place>The Traveller's Inn</place>
    <position x="1844" y="2745" z="0" />
  </location>
  <location>
    <city>Magincia</city>
    <place>The Great Horns Tavern</place>
    <position x="3738" y="2223" z="20" />
  </location>
  <location>
    <city>Jhelom</city>
    <place>The Morning Star Inn</place>
    <position x="1378" y="3817" z="0" />
  </location>
  <location>
    <city>Skara Brae</city>
    <place>The Falconers Inn</place>
    <position x="594" y="2227" z="0" />
  </location>
  <location>
    <city>Vesper</city>
    <place>The Ironwood Inn</place>
    <position x="2771" y="977" z="0" />
  </location>
</start>
